version: 0.0
os: linux
files:
  - source: /  # This points to the root directory where your HTML, CSS, and JS files are located
    destination: /var/www/html  # Destination on the EC2 instance where the web server will serve the files

hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
