version: 0.0
os: linux
files:
  - source: / # This points to the root directory where your files are located
    destination: /var/www/html # The typical directory for serving a website on Linux

hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
