version: 0.0
os: linux
files:
  - source: / # This points to the root directory where your files are located (e.g., HTML, CSS, JS)
    destination: /var/www/html # The destination directory on the EC2 instance (where the web server serves the files)

hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300